// 宮川清実 著書リスト
export const PUBLISHED_BOOKS = [
  {
    id: 1,
    title: 'アミダス人（ひと）: それはプラモデルからはじまった',
    author: '宮川 清実',
    asin: 'B0FXFHGW37',
    coverImage: '/images/books/book1.webp',
    amazonUrl: 'https://www.amazon.co.jp/dp/B0FXFHGW37',
    rating: 4.4,
    reviews: 361,
  },
  {
    id: 2,
    title: 'デザイナーこそエンジニアになれ',
    author: '宮川 清実',
    asin: 'B0FV2DV28C',
    coverImage: '/images/books/book2.webp',
    amazonUrl: 'https://www.amazon.co.jp/dp/B0FV2DV28C',
    rating: 4.7,
    reviews: 542,
  },
  {
    id: 3,
    title: '生きる意味：現代人が見失った人生の真実',
    author: '宮川 清実',
    asin: 'B0FTGDVK9S',
    coverImage: '/images/books/book3.webp',
    amazonUrl: 'https://www.amazon.co.jp/dp/B0FTGDVK9S',
    rating: 4.2,
    reviews: 189,
  },
  {
    id: 4,
    title: '道徳: 覚える教育から、考える教育へ',
    author: '宮川 清実',
    asin: 'B0FX3PDRZQ',
    coverImage: '/images/books/book4.webp',
    amazonUrl: 'https://www.amazon.co.jp/dp/B0FX3PDRZQ',
    rating: 4.6,
    reviews: 423,
  },
  {
    id: 5,
    title: '魂の声: 本来の自分と人生の使命',
    author: '宮川 清実',
    asin: 'B0FP4SVFDF',
    coverImage: '/images/books/book5.webp',
    amazonUrl: 'https://www.amazon.co.jp/dp/B0FP4SVFDF',
    rating: 4.3,
    reviews: 278,
  },
  {
    id: 6,
    title: 'ゴルフ録: 記録データが導く、あなただけのスコアアップ',
    author: '宮川 清実',
    asin: 'B0FWJF2YKC',
    coverImage: '/images/books/book6.webp',
    amazonUrl: 'https://www.amazon.co.jp/dp/B0FWJF2YKC',
    rating: 4.8,
    reviews: 615,
  },
] as const;
