// 宮川清実 著書リスト
export const PUBLISHED_BOOKS = [
  {
    id: 1,
    title: 'アミダス人（ひと）: それはプラモデルからはじまった',
    author: '宮川 清実',
    asin: 'B0FXFHGW37',
    coverImage: '/images/books/book1.webp',
    amazonUrl: 'https://www.amazon.co.jp/dp/B0FXFHGW37',
    rating: 4.4,
    reviews: 361,
  },
  {
    id: 2,
    title: 'デザイナーこそエンジニアになれ',
    author: '宮川 清実',
    asin: 'B0FV2DV28C',
    coverImage: '/images/books/book2.webp',
    amazonUrl: 'https://www.amazon.co.jp/dp/B0FV2DV28C',
    rating: 4.7,
    reviews: 542,
  },
  {
    id: 3,
    title: '生きる意味：現代人が見失った人生の真実',
    author: '宮川 清実',
    asin: 'B0FTGDVK9S',
    coverImage: '/images/books/book3.webp',
    amazonUrl: 'https://www.amazon.co.jp/dp/B0FTGDVK9S',
    rating: 4.2,
    reviews: 189,
  },
  {
    id: 4,
    title: '道徳: 覚える教育から、考える教育へ',
    author: '宮川 清実',
    asin: 'B0FX3PDRZQ',
    coverImage: '/images/books/book4.webp',
    amazonUrl: 'https://www.amazon.co.jp/dp/B0FX3PDRZQ',
    rating: 4.6,
    reviews: 423,
  },
  {
    id: 5,
    title: '魂の声: 本来の自分と人生の使命',
    author: '宮川 清実',
    asin: 'B0FP4SVFDF',
    coverImage: '/images/books/book5.webp',
    amazonUrl: 'https://www.amazon.co.jp/dp/B0FP4SVFDF',
    rating: 4.3,
    reviews: 278,
  },
  {
    id: 6,
    title: 'ゴルフ録: 記録データが導く、あなただけのスコアアップ',
    author: '宮川 清実',
    asin: 'B0FWJF2YKC',
    coverImage: '/images/books/book6.webp',
    amazonUrl: 'https://www.amazon.co.jp/dp/B0FWJF2YKC',
    rating: 4.8,
    reviews: 615,
  },
  {
    id: 8,
    title: '嘘: キャラクターに命を吹き込むデザイン哲学',
    author: '日向 あおば',
    asin: 'B0DJ84G1N6',
    coverImage: '/images/books/book8.webp',
    amazonUrl: 'https://amzn.asia/d/65LXxtY',
    rating: 4.5,
    reviews: 0,
  },
  {
    id: 9,
    title: 'ワンタップが変える世界: 誰も読まないQRコードから、誰もが使う NFCへ',
    author: '宮川 清実',
    asin: '',
    coverImage: '/images/books/book9.webp',
    amazonUrl: '#',
    rating: 4.5,
    reviews: 0,
  },
  {
    id: 10,
    title: '著力: あなたの名前が、Amazonに載る',
    author: '宮川 清実',
    asin: 'B0FXEZ2P',
    coverImage: '/images/books/book10.webp',
    amazonUrl: 'https://amzn.asia/d/0FXEZ2P',
    rating: 4.5,
    reviews: 0,
  },
] as const;
